apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app-container
          image: frontend-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
