name: Deploy to OpenShift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: image-registry.openshift-image-registry.svc:5000
  PROJECT_NAME: venkatakurathitud-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install OpenShift CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | tar xvz
        sudo mv oc /usr/local/bin/

    - name: Login to OpenShift
      run: |
        oc login --server=${{ secrets.OPENSHIFT_SERVER }} \
          --token=${{ secrets.OPENSHIFT_TOKEN }} \
          --insecure-skip-tls-verify=true

    - name: Create or switch to project
      run: |
        oc new-project $PROJECT_NAME || oc project $PROJECT_NAME

    - name: Create or update image streams
      run: |
        oc apply -f - <<EOF
        apiVersion: image.openshift.io/v1
        kind: ImageStream
        metadata:
          name: recipe-app-frontend
        spec:
          lookupPolicy:
            local: false
        ---
        apiVersion: image.openshift.io/v1
        kind: ImageStream
        metadata:
          name: recipe-app-backend
        spec:
          lookupPolicy:
            local: false
        EOF

    - name: Create or update GitHub credentials secret
      run: |
        # Debug token format
        echo "Token format: ${REPO_TOKEN:0:4}"
        
        # Create or update secret with proper token format
        oc apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: github-credentials
        type: kubernetes.io/basic-auth
        stringData:
          username: ${{ secrets.REPO_USERNAME }}
          password: ghp_${{ secrets.REPO_TOKEN }}
        EOF

    - name: Create or update build configurations
      run: |
        export REGISTRY=$REGISTRY
        # Debug Git URL
        echo "Using Git URL: https://${{ secrets.REPO_USERNAME }}:${{ secrets.REPO_TOKEN }}@github.com/venkatTUD/VENKATCA2.git"
        
        # Create build config with direct Git URL
        oc apply -f - <<EOF
        apiVersion: build.openshift.io/v1
        kind: BuildConfig
        metadata:
          name: recipe-app-frontend
        spec:
          source:
            type: Git
            git:
              uri: https://${{ secrets.REPO_USERNAME }}:${{ secrets.REPO_TOKEN }}@github.com/venkatTUD/VENKATCA2.git
              ref: main
            contextDir: frontend-ca2
          strategy:
            type: Docker
            dockerStrategy:
              dockerfilePath: Dockerfile
          output:
            to:
              kind: ImageStreamTag
              name: recipe-app-frontend:latest
          triggers:
            - type: ConfigChange
            - type: ImageChange
        ---
        apiVersion: build.openshift.io/v1
        kind: BuildConfig
        metadata:
          name: recipe-app-backend
        spec:
          source:
            type: Git
            git:
              uri: https://${{ secrets.REPO_USERNAME }}:${{ secrets.REPO_TOKEN }}@github.com/venkatTUD/VENKATCA2.git
              ref: main
            contextDir: backend-ca2
          strategy:
            type: Docker
            dockerStrategy:
              dockerfilePath: Dockerfile
          output:
            to:
              kind: ImageStreamTag
              name: recipe-app-backend:latest
          triggers:
            - type: ConfigChange
            - type: ImageChange
        EOF

    - name: Update build configurations with GitHub credentials
      run: |
        oc patch bc/recipe-app-frontend -p '{"spec":{"source":{"sourceSecret":{"name":"github-credentials"}}}}'
        oc patch bc/recipe-app-backend -p '{"spec":{"source":{"sourceSecret":{"name":"github-credentials"}}}}'

    - name: Start builds
      run: |
        oc start-build recipe-app-frontend
        oc start-build recipe-app-backend

    - name: Wait for builds to complete
      run: |
        # Get the latest build numbers
        FRONTEND_BUILD=$(oc get builds --sort-by=.metadata.creationTimestamp -o name | grep recipe-app-frontend | tail -n 1)
        BACKEND_BUILD=$(oc get builds --sort-by=.metadata.creationTimestamp -o name | grep recipe-app-backend | tail -n 1)
        
        # Wait for builds to complete
        oc wait --for=condition=complete $FRONTEND_BUILD --timeout=10m
        oc wait --for=condition=complete $BACKEND_BUILD --timeout=10m

    - name: Create deployment configuration
      run: |
        export REGISTRY=$REGISTRY
        envsubst < openshift/deploy/deployment-config.yaml | oc create -f -

    - name: Create route configuration
      run: |
        oc create -f openshift/deploy/route-config.yaml

    - name: Wait for deployments to complete
      run: |
        oc rollout status deployment/recipe-app-frontend --timeout=10m
        oc rollout status deployment/recipe-app-backend --timeout=10m
        oc rollout status deployment/mongodb --timeout=10m

    - name: Get route URL
      run: |
        ROUTE_URL=$(oc get route recipe-app-route -o jsonpath='{.spec.host}')
        echo "Application URL: http://$ROUTE_URL"
        echo "ROUTE_URL=$ROUTE_URL" >> $GITHUB_ENV

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "Deployment successful! Application is available at: http://${{ env.ROUTE_URL }}"
        else
          echo "Deployment failed. Check the logs for details."
        fi

    - name: Add MongoDB configuration
      run: |
        oc create -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mongodb
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: recipe-app
              component: mongodb
          template:
            metadata:
              labels:
                app: recipe-app
                component: mongodb
            spec:
              containers:
              - name: mongodb
                image: mongo:latest
                ports:
                - containerPort: 27017
                volumeMounts:
                - name: mongodb-data
                  mountPath: /data/db
              volumes:
              - name: mongodb-data
                persistentVolumeClaim:
                  claimName: mongodb-pvc
        ---
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: mongodb-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: mongodb
        spec:
          ports:
          - port: 27017
            targetPort: 27017
          selector:
            app: recipe-app
            component: mongodb
        EOF

    - name: Add Health Checks
      run: |
        oc patch dc recipe-app -p '{"spec":{"template":{"spec":{"containers":[{"name":"recipe-app-frontend","livenessProbe":{"httpGet":{"path":"/health","port":3000}},"livenessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}}}]}}}}'
        oc patch dc recipe-app -p '{"spec":{"template":{"spec":{"containers":[{"name":"recipe-app-backend","livenessProbe":{"httpGet":{"path":"/health","port":3000}},"livenessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}}}]}}}}'

    - name: Add Resource Limits
      run: |
        oc patch dc recipe-app -p '{"spec":{"template":{"spec":{"containers":[{"name":"recipe-app-frontend","resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"200m","memory":"256Mi"}},"livenessProbe":{"httpGet":{"path":"/health","port":3000}},"livenessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}}}]}}}}'
        oc patch dc recipe-app -p '{"spec":{"template":{"spec":{"containers":[{"name":"recipe-app-backend","resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"200m","memory":"256Mi"}},"livenessProbe":{"httpGet":{"path":"/health","port":3000}},"livenessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}},"readinessProbe":{"httpGet":{"path":"/health","port":3000}}}]}}}}' 